#!/bin/bash
# This git hook will run on the client after a merge or a pull.

gc_git_hook_client_post_merge() {
	GITCID_DIR=${GITCID_DIR:-".gc/"}

	source "${GITCID_DIR}deps.sh" $@
	res_import_deps=$?
	if [ $res_import_deps -ne 0 ]; then
		gitcid_log_warn "${BASH_SOURCE[0]}" $LINENO "Failed importing GitCid dependencies. Things might not work properly, so you might want to address the issue."
	fi

	gitcid_log_info "${BASH_SOURCE[0]}" $LINENO "Invoked client git hook: ${BASH_SOURCE[0]} $@"

	git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep -E --quiet "*"

	if [ $? -eq 0 ]; then
		rm "${GITCID_DIR}.gc-update-available" 2>/dev/null
		gitcid_log_notice "${BASH_SOURCE[0]}" $LINENO "GitCid has just been updated."

	else
		gitcid_log_info "${BASH_SOURCE[0]}" $LINENO "There were no GitCid updates available."
	fi

	gitcid_log_info "${BASH_SOURCE[0]}" $LINENO "The client git hook finished successfully: ${BASH_SOURCE[0]} $@"
}

gc_git_hook_client_post_merge $@
