#!/bin/bash
# This git hook will run on the client after a merge or a pull.

gc_git_hook_client_post_merge() {
	echo "$(date -Ins) [${BASH_SOURCE[0]} - line: $LINENO]	info: Invoked client git hook: ${BASH_SOURCE[0]} $@"

	GITCID_DIR=${GITCID_DIR:-".gc/"}

	source "${GITCID_DIR}deps.sh"
	res_import_deps=$?
	if [ $res_import_deps -ne 0 ]; then
		gitcid_log_err ${BASH_SOURCE[0]} $LINENO "Failed importing GitCid dependencies. I guess it's not going to work, sorry!"
		return $res_import_deps
	fi

	res=$res_import_deps
	if [ $res -ne 0 ]; then
		gitcid_log_err ${BASH_SOURCE[0]} $LINENO "The client git hook failed: ${BASH_SOURCE[0]} $@"
		return $res
	fi

	gitcid_log_info ${BASH_SOURCE[0]} $LINENO "The client git hook finished successfully: ${BASH_SOURCE[0]} $@"
}

gc_git_hook_client_post_merge $@
