#!/bin/bash
# This git hook will run on the client after a merge or a pull.

gc_git_hook_client_post_merge() {
    echo "$(date -Ins)  info: Invoked client git hook: $0 $@"

    GITCID_DIR=${GITCID_DIR:-"./.gc/"}

    source "${GITCID_DIR}deps.sh"
    res_import_deps=$?
    if [ $res_import_deps -ne 0 ]; then
        gc_log_err "Failed importing GitCid log utils. I guess it's not going to work, sorry!"
        return $res_import_deps
    fi

    res=$res_import_deps
    if [ $res -ne 0 ]; then
        gc_log_err "The client git hook failed: $0 $@"
        return $res
    fi

    gc_log_info "The client git hook finished successfully: $0 $@"
}

gc_git_hook_client_post_merge $@
