#!/bin/bash
# This git hook will run on the client before a commit is made.

gc_git_hook_client_pre_commit() {
    echo "$(date -Ins)  info: Git hook invoked on client: $0 $@"

    GITCID_DIR=${GITCID_DIR:-"./.gc/"}

    source "${GITCID_DIR}deps.sh"
    res_import_deps=$?
    if [ $res_import_deps -ne 0 ]; then
        gc_log_err "Failed importing GitCid log utils. I guess it's not going to work, sorry!"
        return $res_import_deps
    fi

    res=$res_import_deps
    if [ $res -ne 0 ]; then
        gc_log_err "The client git hook failed: $0 $@"
        return $res
    fi

    gc_log_info "The git hook finished successfully."
}

gc_git_hook_client_pre_commit $@
