#!/usr/bin/env bash
# This git hook will run on the client after a merge or a pull.

gc_git_hook_client_post_merge() {
	GITCID_DIR=${GITCID_DIR:-".gc/"}

  echo "hostname=$(hostname)"
  echo ""
  echo "USER=$(whoami)"
  echo ""

  # sudo chown -R $USER: "${PWD}" 2>/dev/null
  # sudo chown -R $USER: "${GITCID_DIR}.." 2>/dev/null
  # sudo chown -R $USER: "${GITCID_DIR}../" 2>/dev/null
  # sudo chown -R $USER: "${GITCID_DIR}" 2>/dev/null
  # sudo chown -R $USER: "${GITCID_DIR}../.git" 2>/dev/null
  # sudo chown -R $USER: * 2>/dev/null
  # sudo chown -R $USER: ./* 2>/dev/null
  # sudo chown -R $USER: ./ 2>/dev/null
  # sudo chown -R $USER: . 2>/dev/null

	source "${GITCID_DIR}deps.sh" $@
	res_import_deps=$?
	if [ $res_import_deps -ne 0 ]; then
		gitcid_log_warn "${BASH_SOURCE[0]}" $LINENO "Failed importing GitCid dependencies. Things might not work properly, so you might want to address the issue."
	fi

	gitcid_log_info "${BASH_SOURCE[0]}" $LINENO "Invoked client git hook: ${BASH_SOURCE[0]} $@"

	rm "${GITCID_DIR}.gc-update-available" 2>/dev/null
	gitcid_log_update "${BASH_SOURCE[0]}" $LINENO "GitCid has just been updated."

  echo "hostname=$(hostname)"
  echo ""
  echo "USER=$(whoami)"
  echo ""

  # sudo chown -R $USER: "${PWD}" 2>/dev/null
  # sudo chown -R $USER: "${GITCID_DIR}.." 2>/dev/null
  # sudo chown -R $USER: "${GITCID_DIR}../" 2>/dev/null
  # sudo chown -R $USER: "${GITCID_DIR}" 2>/dev/null
  # sudo chown -R $USER: "${GITCID_DIR}../.git" 2>/dev/null
  # sudo chown -R $USER: * 2>/dev/null
  # sudo chown -R $USER: ./* 2>/dev/null
  # sudo chown -R $USER: ./ 2>/dev/null
  # sudo chown -R $USER: . 2>/dev/null

	gitcid_log_info "${BASH_SOURCE[0]}" $LINENO "The client git hook finished successfully: ${BASH_SOURCE[0]} $@"
}

gc_git_hook_client_post_merge $@
